# Generated by Django 4.2.6 on 2023-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.TextField(blank=True),
        ),
    ]
